# Spring Boot Actuator Configuration
# This is a default configuration that can be included in microservices

# Management endpoints configuration
management:
  endpoints:
    web:
      # Base path for actuator endpoints
      base-path: /actuator
      # Exposure settings - by default we expose a limited set of endpoints
      exposure:
        include: health,info,metrics,loggers,skutter-loggers
  
  # Health endpoint configuration
  health:
    show-details: when_authorized
    
  # Info endpoint configuration
  info:
    env:
      enabled: true
    git:
      enabled: true
      mode: simple
    build:
      enabled: true
    java:
      enabled: true
      
  # Metrics endpoint configuration
  metrics:
    tags:
      application: ${spring.application.name}
  
  # Endpoint discovery over JMX should be disabled by default
  endpoint:
    jmx:
      exposure:
        exclude: "*"

# Skutter-specific actuator configuration
skutter:
  actuator:
    enabled: true
    # By default, authentication is required for sensitive endpoints
    require-authentication: true
    endpoints:
      health: true
      info: true
      metrics: true
      loggers: true
      env: false
      beans: false
      threaddump: false
      heapdump: false 